server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: chinesedream
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinesedream?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #**d如果不保存日志文件使用
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭
  mapper-locations: classpath:com/atguigu/serviceorganization/mapper/xml/*.xml #这个mapper和pom.xml的resourses配置要一起配置才行
  ## 'mybatis-plus '时,驼峰命名映射是自动开启的
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0